### ISSUE TITLE
Retro Funding 5: Voting API

### ISSUE THREAD

**Issue by JSeiferth** [voteagora/op-atlas#181]
provide API to power the voting client for Retro Funding 5. 

1. Scope [here](https://agoraxyz.notion.site/RetroFunding-R5-API-Roadmap-4ab651834b194ab98497a8f0f4c14e87?pvs=4)
2. Timeline: Completion by Sept 20th

### Milestones
- [x] Formal API schema & docs
- [x] Projects API with mock data
- [x] Ballots API with mock data (ex distributions methods)
- [x] Distribution strategies with mock data
- [x] Prod release
