### ISSUE TITLE
Technical Strategy for OP Atlas

### ISSUE THREAD

**Issue by JSeiferth** [voteagora/op-atlas#344]
[Doc here](https://www.notion.so/agoraxyz/Atlas-Technical-strategy-144528b28fc480e78b6edef21332e7cb)

Issues: 
- [x] https://github.com/voteagora/op-atlas/issues/360
- [x] https://github.com/voteagora/op-atlas/issues/352
- [ ] https://github.com/voteagora/op-atlas/issues/351

**Comment by JSeiferth** [comment]
@stepandel is this done? can we close the ticket?

**Comment by stepandel** [comment]
yup this is done
