### ISSUE TITLE
Guest voter signup

### ISSUE THREAD

**Issue by JSeiferth** [voteagora/op-atlas#350]
Doc [here](https://www.notion.so/Guest-Voter-Signup-Feb-2025-15a5831e3452803fb955c7122fc9cd95)

Guest Voter signup consists of the following steps:
- To be eligible, participants must have created a profile in OP Atlas and meet certain requirements
- Community contributors will have to connect Discord, other eligible participants are already able to set up their profile in the right way
- Eligible users will be emailed a registration form, for which we need an email template and to import the emails into Mailchimp

**Engineering issues:**

- [x] https://github.com/voteagora/op-atlas/issues/414
- [x] https://github.com/voteagora/op-atlas/issues/452
- [x] https://github.com/voteagora/op-atlas/issues/466
- [x] https://github.com/voteagora/op-atlas/issues/495

**Design issues:**
Connect Discord
- [x] https://github.com/voteagora/op-atlas/issues/378

Email template
- [x] https://github.com/voteagora/op-atlas/issues/415
