### ISSUE TITLE
Q4/Q1 Roadmap

### ISSUE THREAD

**Issue by JSeiferth** [voteagora/op-atlas#377]
[2025 overview doc ](https://www.notion.so/Retro-Funding-2025-1515831e345280f38ef1d77e774a0c69)

### Election profiles are live 
Profiles in OP-Atlas will allow Governance participants to get more insights into election candidates
- [x] https://github.com/voteagora/op-atlas/issues/338

### Voter Sign up is live
Stakeholders across the Collective are able to register to be a voter in Retro Funding in Season 7
- [x] https://github.com/voteagora/op-atlas/issues/350

### Retro Funding Sign up is live
The sign up and application process for Onchain Builder and Dev Tooling mission are live.
- [x] https://github.com/voteagora/op-atlas/issues/339
- [x] https://github.com/voteagora/op-atlas/issues/353

### Retro Funding rewards payouts are live
Builders who are participating in Retro Funding are able to claim their rewards and track their impact
- [x] https://github.com/voteagora/op-atlas/issues/340
- [x] https://github.com/voteagora/op-atlas/issues/341
- [ ] https://github.com/voteagora/op-atlas/issues/354
- [ ] https://github.com/voteagora/op-atlas/issues/349
- [ ] https://github.com/voteagora/op-atlas/issues/379
